In [1]:
import numpy as np
import math

# Eigenvalues and Eigenvectors Solver class

### Note That
<p> The class can solve for any number of dimentions</p>

### How to use
<ol>
    <li> set instance of the class and the constructor must have 2 arguments (dimention (number of rows or columns),accuracy)  
    <p> <strong>Directions</strong>: square_n: the dimentions of the square matrix (ex: "square_n=2" if (2 x 2) square matrix)
        accuracy: the accuracy to which you want to approach
        <br>
        ex:- accuracy = 2 => accuracy to 2 decimal places</p>
    </li>
    <br>
    <li>
        <div>eigen = Eigen(3,2)</div>
        <br>
        <div>val_arr = [2,1,1,2,3,2,1,1,2]  #input can be array</div>
        <div>eigen.input_matrix(val_arr) if the constructor has dimension or</div>
        <br>
        <div>eigen.input_matrix(2,1,1,2,3,2,1,1,2) if the constructor has dimension or</div>
        <br>
        <div>eigen.input_matrix(2,1,1,2,3,2,1,1,2,n=3) if the constructor doesn't have the dimension</div>
    </li>
    <br>
    <li>
        eigen.calculate() to calculate eigen values and eigen vectors
    </li>

In [2]:
class Eigen:
    def __init__(self,square_n,accuracy):
        """
        square_n: the dimentions of the square matrix (ex: "square_n=2" if (2 x 2) square matrix)
        accuracy: the accuracy to which you want to approach
        ex:- accuracy = 2 => accuracy to 2 decimal places
        """
        self.n = square_n
        self.A = None  # matrix A
        self.v = np.ones(self.n).astype(float).reshape(self.n,1)  # matrix v
        self.accuracy = accuracy  #setting accuracy
        self.eigen_value = None  # current Eigenvalue
        self.eigen_vector = None  # current Eigenvector
        self.prev_val = 0
        
    #Matrix input
    def input_matrix(self,*args,n=None):
        if n==None: n = self.n
        if len(args) != pow(n,2):
            print(len(args),n)
            raise ValueError("the array arguments must have the same size of the square array i.e (for n^2 arguments for nxn matrix)")
        elif n!=self.n:
            self.n = n
            self.v = np.ones(n).astype(float).reshape(n,1)
        count = 0
        string = ""
        for i in args:
            count+=1
            if count == n:
                count =0
                string+=f" {i}; "
            else:
                string+=f" {i} "
        string = string[:-2]
        self.A =  np.matrix(string).astype(float)
        print(self.A)
        
    # calculation method
    def calculate(self):
        iteration = 1
        self._calculateEigenVector()
        self._calculateEigenValue()
        print(f"iteration {iteration}\neigen value: {self.eigen_value} \neigen_vector: {self.eigen_vector}")
        while(math.fabs(self.eigen_value -self.prev_val)>pow(10,-self.accuracy)):
            print("################################")
            iteration+=1
            self.prev_val = self.eigen_value
            self._calculateEigenVector()
            self._calculateEigenValue()
            print(f"iteration {iteration}\neigen value: {self.eigen_value} \neigen_vector: {self.eigen_vector}")
        return self.eigen_value,self.eigen_vector
            
    #Calculate Eigenvector
    def _calculateEigenVector(self):
        """
        Viter(n+1) = A.V(iter(n))
        """
        self.v = self.A.dot(self.v)
        self.v = self.v/self.v[1,0]
        self.eigen_vector = self.v
        return self.eigen_vector
    
    #Calculate Eigenvalue
    def _calculateEigenValue(self):
        """
        numenator = (transpose(A.v)).v
        denomenator = transpose(v).v
        EigenValue = numenator/denomenator
        """
        self.eigen_value = ((self.A.dot(self.v)).transpose().dot(self.v))/self.v.transpose().dot(self.v)[0,0]
        return self.eigen_value

## Example on 2D Matrix

In [3]:
eigen = Eigen(2,2)

In [4]:
eigen.input_matrix(5,4,1,2)

[[5. 4.]
 [1. 2.]]


In [5]:
eigen.calculate()

iteration 1
eigen value: [[6.2]] 
eigen_vector: [[3.]
 [1.]]
################################
iteration 2
eigen value: [[6.03626943]] 
eigen_vector: [[3.8]
 [1. ]]
################################
iteration 3
eigen value: [[6.00611403]] 
eigen_vector: [[3.96551724]
 [1.        ]]
################################
iteration 4
eigen value: [[6.00102087]] 
eigen_vector: [[3.99421965]
 [1.        ]]


(matrix([[6.00102087]]), matrix([[3.99421965],
         [1.        ]]))

## Example on 3D Matrix

In [6]:
eigen.input_matrix(2,1,1,2,3,2,1,1,2,n=3)

[[2. 1. 1.]
 [2. 3. 2.]
 [1. 1. 2.]]


In [7]:
eigen.calculate()

iteration 1
eigen value: [[5.07407407]] 
eigen_vector: [[0.57142857]
 [1.        ]
 [0.57142857]]
################################
iteration 2
eigen value: [[5.01721664]] 
eigen_vector: [[0.51351351]
 [1.        ]
 [0.51351351]]
################################
iteration 3
eigen value: [[5.00353337]] 
eigen_vector: [[0.5026738]
 [1.       ]
 [0.5026738]]
################################
iteration 4
eigen value: [[5.00071023]] 
eigen_vector: [[0.50053362]
 [1.        ]
 [0.50053362]]


(matrix([[5.00071023]]), matrix([[0.50053362],
         [1.        ],
         [0.50053362]]))