In [1]:
import numpy as np
import math

In [2]:
class Eigen:
    def __init__(self,a,b,c,d,accuracy):
        """
        a,b,c,d: Elements of a 2x2 square matrix
        accuracy: the accuracy to which you want to approach
        ex:- accuracy = 2 => accuracy to 2 decimal places
        """
        self.A = np.matrix(f"{a} {b};{c} {d}").astype(float)  # matrix A
        self.v = np.ones(2).astype(float).reshape(2,1)  # matrix v
        self.accuracy = accuracy  #setting accuracy
        self.eigen_value = None  # current Eigenvalue
        self.eigen_vector = None  # current Eigenvector
        self.prev_val = 0
        
    # calculation method
    def calculate(self):
        iteration = 1
        self._calculateEigenVector()
        self._calculateEigenValue()
        print(f"iteration {iteration}\neigen value: {self.eigen_value} \neigen_vector: {self.eigen_vector}")
        while(math.fabs(self.eigen_value -self.prev_val)>pow(10,-self.accuracy)):
            print("################################")
            iteration+=1
            self.prev_val = self.eigen_value
            self._calculateEigenVector()
            self._calculateEigenValue()
            print(f"iteration {iteration}\neigen value: {self.eigen_value} \neigen_vector: {self.eigen_vector}")
        return self.eigen_value,self.eigen_vector
            
    #Calculate Eigenvector
    def _calculateEigenVector(self):
        """
        Viter(n+1) = A.V(iter(n))
        """
        self.v = self.A.dot(self.v)
        self.v = self.v/self.v[1,0]
        self.eigen_vector = self.v
        return self.eigen_vector
    
    #Calculate Eigenvalue
    def _calculateEigenValue(self):
        """
        numenator = (transpose(A.v)).v
        denomenator = transpose(v).v
        EigenValue = numenator/denomenator
        """
        self.eigen_value = ((self.A.dot(self.v)).transpose().dot(self.v))/self.v.transpose().dot(self.v)[0,0]
        return self.eigen_value

In [3]:
o = Eigen(5,4,1,2,accuracy = 2)

In [4]:
o.calculate()

iteration 1
eigen value: [[6.2]] 
eigen_vector: [[3.]
 [1.]]
################################
iteration 2
eigen value: [[6.03626943]] 
eigen_vector: [[3.8]
 [1. ]]
################################
iteration 3
eigen value: [[6.00611403]] 
eigen_vector: [[3.96551724]
 [1.        ]]
################################
iteration 4
eigen value: [[6.00102087]] 
eigen_vector: [[3.99421965]
 [1.        ]]


(matrix([[6.00102087]]), matrix([[3.99421965],
         [1.        ]]))

In [5]:
#Assignment 3 page 13 a
p13a = Eigen(1,-1,2,4,accuracy = 3)
p13a.calculate()

iteration 1
eigen value: [[4.]] 
eigen_vector: [[0.]
 [1.]]
################################
iteration 2
eigen value: [[3.58823529]] 
eigen_vector: [[-0.25]
 [ 1.  ]]
################################
iteration 3
eigen value: [[3.3438914]] 
eigen_vector: [[-0.35714286]
 [ 1.        ]]
################################
iteration 4
eigen value: [[3.20993137]] 
eigen_vector: [[-0.41304348]
 [ 1.        ]]
################################
iteration 5
eigen value: [[3.13217963]] 
eigen_vector: [[-0.44520548]
 [ 1.        ]]
################################
iteration 6
eigen value: [[3.08490367]] 
eigen_vector: [[-0.46475771]
 [ 1.        ]]
################################
iteration 7
eigen value: [[3.05524131]] 
eigen_vector: [[-0.47704448]
 [ 1.        ]]
################################
iteration 8
eigen value: [[3.03624215]] 
eigen_vector: [[-0.48492699]
 [ 1.        ]]
################################
iteration 9
eigen value: [[3.0239069]] 
eigen_vector: [[-0.4900513]
 [ 1.       ]]
####

(matrix([[3.00137187]]), matrix([[-0.49942843],
         [ 1.        ]]))

In [6]:
#Assignment 3 page 14 b
p14b = Eigen(5,1,-3,1,3)
p14b.calculate()

iteration 1
eigen value: [[5.2]] 
eigen_vector: [[-3.]
 [ 1.]]
################################
iteration 2
eigen value: [[4.59459459]] 
eigen_vector: [[-1.4]
 [ 1. ]]
################################
iteration 3
eigen value: [[4.27411168]] 
eigen_vector: [[-1.15384615]
 [ 1.        ]]
################################
iteration 4
eigen value: [[4.13096559]] 
eigen_vector: [[-1.06896552]
 [ 1.        ]]
################################
iteration 5
eigen value: [[4.06397919]] 
eigen_vector: [[-1.03278689]
 [ 1.        ]]
################################
iteration 6
eigen value: [[4.03161806]] 
eigen_vector: [[-1.016]
 [ 1.   ]]
################################
iteration 7
eigen value: [[4.01571679]] 
eigen_vector: [[-1.00790514]
 [ 1.        ]]
################################
iteration 8
eigen value: [[4.00783542]] 
eigen_vector: [[-1.00392927]
 [ 1.        ]]
################################
iteration 9
eigen value: [[4.00391198]] 
eigen_vector: [[-1.00195886]
 [ 1.        ]]
#########

(matrix([[4.00097692]]), matrix([[-1.00048864],
         [ 1.        ]]))